- name: Pull the nginx:alpine-slim image
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    source: pull
    force_source: yes

- name: Create nginx container (recreate if a new image is pulled)
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    network_mode: "{{ docker_network_mode }}"
    restart_policy: "{{ docker_container_restart_policy }}"
    volumes:
      - "/var/log/nginx:/var/log/nginx"

- name: Create fail2ban container
  community.docker.docker_container:
    name: fail2ban
    image: crazymax/fail2ban:latest
    network_mode: host
    privileged: true
    restart_policy: always
    volumes:
      - "/var/log/nginx:/var/log/nginx"
      - "/var/run/fail2ban:/var/run/fail2ban"