---
- name: Include configure from shared role
  ansible.builtin.include_role:
    name: shared
    tasks_from: install_packages

- name: Import docker tasks
  ansible.builtin.include_tasks: docker.yml

- name: Import nginx configuration tasks
  ansible.builtin.include_tasks: configure.yml
