- name: Copy configuration file into instance
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/16/main/pg_hba.conf

- name: Change password for user postgres
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user: 
    name: postgres
    password: postgres
