- name: Pull the webserver image
  docker_image:
    name: francoisgib/dac-tp5:webserver
    source: pull
    force_source: yes # Always pull the latest image

- name: Create webserver container (recreate if a new image is pulled)
  docker_container:
    name: webserver
    image: francoisgib/dac-tp5:webserver
    network_mode: host
    restart_policy: always
    hostname: "{{ ansible_hostname }}"

- name: Import webservers network configuration tasks
  include_tasks: webservers_network_configuration.yml

- name: Import network common configuration tasks
  include_tasks: ../common/network_configuration.yml