- name: Gather facts (just required configuration facts)
  ansible.builtin.setup:
    filter:
      - 'ansible_hostname'

- name: Import accept policy tasks
  include_tasks: ../../common/accept_policy.yml

- name: Pull the webserver image
  docker_image:
    name: francoisgib/dac-tp5:webserver
    source: pull
    force_source: yes # Always pull the latest image

- name: Import webservers network configuration tasks
  include_tasks: webservers_network_configuration.yml

- name: Create webserver container (recreate if a new image is pulled)
  docker_container:
    name: webserver
    image: francoisgib/dac-tp5:webserver
    network_mode: host
    restart_policy: always
    hostname: "{{ ansible_hostname }}"