- name: Include common configuration
  import_playbook: common/common_configuration.yml

- name: Include webservers configuration
  import_playbook: webservers/webservers_configuration.yml

- name: Include nginx proxy configuration
  import_playbook: nginx/nginx_configuration.yml