- name: Webservers configuration
  hosts: webservers
  roles:
    - webserver

- name: Master and slaves db configuration
  hosts: slaves:master
  roles:
    - postgres

- name: Master configuration
  hosts: master
  roles:
    - master

- name: Slaves configuration
  hosts: slaves
  roles:
    - slave

- name: Proxy configuration
  hosts: proxy
  roles:
    - nginx
    - pgpool

- import_playbook: monitoring/playbook.yml
- import_playbook: nftables/nftables_config.yml
