- name: Common configuration
  remote_user: ubuntu
  become: true
  hosts: proxy:webservers
  gather_facts: no
  tasks:
    - name: Import common tasks
      include_tasks: common/common_tasks.yml

- name: Include webservers configuration
  import_playbook: webservers/webservers_configuration.yml

- name: Include nginx proxy configuration
  import_playbook: nginx/nginx_configuration.yml