---
- name: Gather facts (just required configuration facts)
  ansible.builtin.setup:
    filter: "{{ required_facts }}"
  when: 
    - "required_facts is defined"
    - "required_facts | length > 0"
...