- name: Import accept policy tasks
  include_tasks: ../../common/accept_policy.yml

- name: Allow input on http-alt port (8080)
  iptables:
    chain: INPUT
    protocol: tcp
    source: "{{ webservers_subnet }}"
    source_port: http-alt
    jump: ACCEPT

- name: Allow output on http-alt port (8080)
  iptables:
    chain: OUTPUT
    protocol: tcp
    destination: "{{ webservers_subnet }}"
    destination_port: http-alt
    jump: ACCEPT

- name: Allow input on http port
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: http
    jump: ACCEPT

- name: Allow output on http port
  iptables:
    chain: OUTPUT
    protocol: tcp
    source_port: http
    jump: ACCEPT

- name: Import allow ssh tasks
  include_tasks: ../../common/allow_ssh.yml

- name: Import drop policy tasks
  include_tasks: ../../common/drop_policy.yml