- name: Proxy configuration
  remote_user: ubuntu
  become: true
  hosts: proxy

  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted

  tasks:
    - name: Install haproxy
      apt:
        name: haproxy
        state: present

    - name: Copy Haproxy configuration file
      template:
        src: ../haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy