{
 "title": "Pgpool Metrics",
 "tags": [ "pgpool" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backend_nodes",
    "query": {
     "query": "label_values(pgpool2_pool_nodes_status{}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgpool2_pool_nodes_status", "legendFormat": "{{role}}" }
   ]
  },
  {
   "title": "Active Connections Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgpool2_frontend_used_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Connectios",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "targets": [
    { "expr": "pgpool2_frontend_used", "legendFormat": "{{__name__}}" },
    { "expr": "pgpool2_frontend_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Replication delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pgpool2_pool_nodes_replication_delay{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    },
    {}
   ]
  },
  { "title": "Error Message Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Error Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_error_cnt{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Fatal Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_fatal_cnt{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Panic Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_panic_cnt{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  { "title": "SQL Command Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "SELECT statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_select_cnt{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "DELETE statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 17 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_delete_cnt{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "INSERT statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_insert_cnt{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "UPDATE statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_update_cnt{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "DDL statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 23 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_ddl_cnt{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Other statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 23 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_other_cnt{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Number of health check count in total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_total_count{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of Successful Health Check ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_success_count{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of failed health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_fail_count{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of skipped health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_skip_count{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of retried health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_retry_count{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of maximum retried health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_max_retry_count{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of average retried health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 35 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_average_retry_count{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Average health check duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_average_duration{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Minimum health check duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_min_duration{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Maximum health check duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_max_duration{hostname=~\"$backend_nodes\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  { "title": "Query Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Query Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgpool2_pool_cache_cache_hit_ratio",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}