- name: Wait for target connection to become reachable/usable
  wait_for_connection:
    timeout: 600  

- name: Update apt cache
  apt:
    update_cache: true
  retries: 2

- name: Install required system packages
  apt:
    pkg:
      - python3-pip
    state: latest
    update_cache: true


- name: Install Docker
  apt:
    name: docker.io
    state: present
  retries: 2

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Allow loopback input 
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT 

- name: Allow loopback output
  iptables:
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT