---
- name: Include configure from shared role
  ansible.builtin.include_role:
    name: shared
    tasks_from: install_packages

- name: Generate dynamic env file
  ansible.builtin.template:
    src: env.j2
    dest: ./env

- name: Pull the pgpool bitnami image
  community.docker.docker_image:
    name: "bitnami/pgpool"
    source: pull
    force_source: yes

- name: Create PgPool container (recreate if a new image is pulled)
  community.docker.docker_container:
    name: pgpool
    image: "bitnami/pgpool"
    network_mode: "host"
    restart_policy: always
    env_file: ./env
