- name: Pull the webserver image
  community.docker.docker_image:
    name: francoisgib/dac-tp5:webserver
    source: pull
    force_source: yes # Always pull the latest image

- name: Create webserver container (recreate if a new image is pulled)
  community.docker.docker_container:
    name: webserver
    image: "francoisgib/dac-tp5:webserver"
    network_mode: host
    restart_policy: always
    hostname: "{{ ansible_hostname }}"
    env:
      POSTGRES_URL: "{{ proxy_ip }}"
      POSTGRES_PORT: "{{ postgres_port | string }}"