---
- name: Import webservers tasks
  ansible.builtin.include_tasks: configuration.yml

- name: Import webservers tasks
  ansible.builtin.include_tasks: docker.yml

# - name: Import network tasks
#   include_tasks: network.yml
...