---
- name: Update web servers
  remote_user: ubuntu
  become: true
  hosts: myhosts
  gather_facts: no
  tasks:
    - name: Wait for connection to instances
      wait_for_connection:
        delay: 60
        timeout: 300

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Copy file
      copy:
        src: ./index.html
        dest: /home/ubuntu/nginx/

    - name: Create nginx container
      docker_container:
        name: nginx
        image: nginx
        ports:
          - 80:80
        volumes:
          - /home/ubuntu/nginx:/usr/share/nginx/html

    - name: Allow loopback input 
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT 

    - name: Allow loopback output
      iptables:
        chain: OUTPUT
        out_interface: lo
        jump: ACCEPT
    
    - name: Allow input on port https (443)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: https
        jump: ACCEPT

    - name: Allow input on port http (80)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: http
        jump: ACCEPT

    - name: Allow input on ssh port (22)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: ssh
        jump: ACCEPT

    - name: Allow output on ssh port (22)
      iptables:
        chain: OUTPUT
        protocol: tcp
        ctstate:
          - ESTABLISHED
        source_port: ssh
        jump: ACCEPT

    - name: Allow input on https port (443)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: https
        jump: ACCEPT
    
    - name: Allow output on https port (443)
      iptables:
        chain: OUTPUT
        protocol: tcp
        source_port: https
        jump: ACCEPT

    - name: Allow input on http port (80)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: http
        jump: ACCEPT

    - name: Allow output on http port (80)
      iptables:
        chain: OUTPUT
        protocol: tcp
        source_port: http
        jump: ACCEPT

    - name: Set the policy for the OUTPUT chain to DROP
      iptables:
        chain: OUTPUT
        policy: DROP

    - name: Set the policy for the INPUT chain to DROP
      iptables:
        chain: INPUT
        policy: DROP
