---
- name: Update web servers
  remote_user: ubuntu
  become: true
  hosts: myhosts
  tasks:
    - name: Ping hosts
      ping:

    - name: Update apt and install postgresql
      apt:
        name: postgresql
        state: latest
        update_cache: true

    - name: Set wal_level to hot_standby (permit readonly on slaves)
      community.postgresql.postgresql_set:
        name: wal_level
        value: hot_standby

    - name: Set hot_standby (allow readonly requests)
      community.postgresql.postgresql_set:
        name: hot_standby
        value: on

    - name: Set max_wal_senders to number of replicates (2)
      community.postgresql.postgresql_set:
        name: max_wal_senders
        value: 2

    