- name: Master slaves common configuration
  remote_user: ubuntu
  become: true
  hosts: master:slaves
  tasks:
  - name: Set wal_level to hot_standby
    community.postgresql.postgresql_set:
      name: wal_level
      value: hot_standby
    become: yes
    become_user: postgres

  - name: Set max_wal_senders to number of replicates (2)
    community.postgresql.postgresql_set:
      name: max_wal_senders
      value: 2
    become: yes
    become_user: postgres

  - name: Set wal_keep_segments to 256
    community.postgresql.postgresql_set:
      name: wal_keep_segments
      value: 256
    become: yes
    become_user: postgres

  - name: Set checkpoint_segments to 8
    community.postgresql.postgresql_set:
      name: checkpoint_segments
      value: 8
    become: yes
    become_user: postgres