---
- name: Update web servers
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: su
  become_exe: sudo su -
  hosts: myhosts
  tasks:
    - name: Allow input on ssh port
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "22"
        jump: ACCEPT

    - name: Allow output on ssh port
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        ctstate:
          - ESTABLISHED
        source_port: "22"
        jump: ACCEPT

    - name: Allow input on port 8000
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "8000"
        jump: ACCEPT

    - name: Allow output on port 8000
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        source_port: "8000"
        jump: ACCEPT

    - name: Set the policy for the OUTPUT chain to DROP
      ansible.builtin.iptables:
        chain: OUTPUT
        policy: DROP

    - name: Set the policy for the INPUT chain to DROP
      ansible.builtin.iptables:
        chain: INPUT
        policy: DROP

    - name: Set the policy for the FORWARD chain to DROP
      ansible.builtin.iptables:
        chain: FORWARD
        policy: DROP
