- name: Nginx configuration update
  remote_user: ubuntu
  become: true
  hosts: proxy
  gather_facts: no
  tasks:
    - name: Copy new configuration into instance
      template:
        src: ../nginx/nginx.conf
        dest: nginx.conf

    - name: Copy new configuration into container
      community.docker.docker_container_copy_into:
        container: nginx-load-balancer
        path: nginx.conf
        container_path: /etc/nginx/nginx.conf

    - name: Remove config file in instance
      file:
        path: nginx.conf
        state: absent

    - name: Reload Nginx config without downtime
      community.docker.docker_container_exec:
        container: nginx-load-balancer
        command: /bin/sh -c "nginx -s reload"
