- name: Nginx configuration
  remote_user: ubuntu
  become: true
  hosts: proxy
  gather_facts: no
  tasks:
    - name: Gather facts (just required configuration facts)
      setup:
        filter:
          - 'ansible_hostname'

    - name: Import accept policy tasks
      include_tasks: ../common/accept_policy.yml

    - name: Pull the nginx-load-balancer image
      docker_image:
        name: "{{ docker_repository }}:nginx-load-balancer"
        source: pull
        force_source: yes # Always pull the latest image

    - name: Create nginx container (recreate if a new image is pulled)
      docker_container:
        name: nginx-load-balancer
        image: "{{ docker_repository }}:nginx-load-balancer"
        network_mode: host
        restart_policy: always

    - name: Import nginx network configuration tasks
      include_tasks: tasks/nginx_network_configuration.yml