- name: Allow input on http port (80)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: http
    jump: ACCEPT

- name: Allow output on http port (80)
  iptables:
    chain: OUTPUT
    protocol: tcp
    source_port: http
    jump: ACCEPT

# - name: Import network common configuration tasks
#   include_tasks: ../common/network_configuration.yml