- name: Pull the nginx node exporter image
  docker_image:
    name: nginx/nginx-prometheus-exporter:1.3.0
    source: pull

- name: Create Nginx node exporter container # Port 9113
  docker_container:
    name: nginx_exporter
    image: nginx/nginx-prometheus-exporter:1.3.0
    network_mode: host
    command:
      - "--nginx.scrape-uri=http://localhost:9999/metrics"
    restart_policy: unless-stopped


- name: Pull the fail2ban node exporter image
  docker_image:
    name: registry.gitlab.com/hctrdev/fail2ban-prometheus-exporter
    source: pull

- name: Create fail2ban node exporter container # Port 9191
  docker_container:
    name: fail2ban-exporter
    image: registry.gitlab.com/hctrdev/fail2ban-prometheus-exporter
    network_mode: host
    restart_policy: unless-stopped
    privileged: true
    volumes:
      - /var/run/fail2ban:/var/run/fail2ban:ro
